src/components/elements/FileUpload.js, src/components/forms/CarrierForm.js, src/components/forms/SpeechForm.js, src/components/pages/internal/CarriersList.js, src/components/pages/internal/SpeechServicesList.js
This PR:
- Adds account selector to speech form
- Sends `account_sid` with payload if selected in speech form
- Otherwise sends `service_provider_sid` with payload if no account is selected in speech form
- Adds account selector to speech credentials list view
- Adds account selector to carrier list view
- Adds file input pseudo element styling for Mozilla so file input button UI is visible in Firefox
=> Add account sid selector to speech form

src/components/elements/AddButton.js, src/data/AwsRegions.js
The add button on the internal template can't be clicked because it's under the list component. I've added a z-index CSS property to send it to the top. Doing so the add button can be clicked anywhere down the list and not just at the beggining.
=> Add z-index property to Add button

src/components/forms/AccountForm.js
I want to make sure the variables look right first before making any stylistic changes.
As for stylistic changes, it is embarrasing to admit that I was spending the last hours to align text. There is more into it. The form is a grid because it has the attribute `large`. So, in order for the text to stay in one line, we either tread the on the grid form or have more column space for text to render (this does not change the content box side, yet). This will affect other labels in this page. But it only works for accounted render resolution. So on some devices, it will become two lines. So we can do something like render the form at device's resolution, something like that. But that would change a bit more things. 
Anyway, here is what it looks like.
If the variable looks okay then I can try …
=> Implementing SIPREC application selection (#66)

src/components/forms/AccountForm.js
Not sure why the other one just automatically close, probably I pushed before making a fix commit
=> remove dummy text from siprec tooltip

.gitignore, src/containers/internal/views/phone-numbers/index.tsx
@xquanluu It's probably tough to totally explain clearly what I'm talking about in my PR review for #104. Here's a commit pointed back at your branch showing the intended implementation for this bug to be fully functional with regard to the proposed solution of requiring account selection before you can assign applications.
Here's also some screenshots of this branch in action:
=> Working solution to issue #104

src/api/types.ts, src/containers/internal/views/carriers/form.tsx
This PR adds the new inputs to the Carrier form on the main branch. 
Inputs added:
- register_from_user 
- register_from_domain 
- register_public_ip_in_contact
=> Add inputs to Carrier form to support outbound registration

src/api/types.ts, src/containers/internal/views/speech-services/form.tsx, src/containers/internal/views/speech-services/utils.ts, src/vendor/index.tsx, src/vendor/speech-recognizer/nuance-speech-recognizer-lang.ts, src/vendor/speech-synthesis/nuance-speech-synthesis-lang.ts, src/vendor/types.ts
Added to:
1. Speech provider with credentials clientId and secret (the post request works)
2. Speech Synthesis Vendor with sample mapping of the voices (need your input @davehorton)
3. Speech Recognizer Vendor (I was not sure about this, please let me know)
Question for No2 above, what values do you need to be saved, @davehorton ? Currently, this is the mapping I used:
```
{
code: "en-US",
name: "English (United States)",
voices: [
{ value: "allison", name: "Allison (standard)", model: "standard" },
{ value: "ava-ml", name: "Ava-Ml (enhanced)", model: "enhanced" },
],
},
```
or should we have voices[0].value" filled with the object like this:
```
{
"language": "ar-ww",
"name": "Laila",
"model": "standard",
"gender": "female"
}
```
Depends on what you need here.
=> Add nuance speech provider

src/api/index.ts, src/api/types.ts, src/containers/internal/views/carriers/form.tsx
Added a post request to get the sid for the template and then navigate to the template.
This way we navigate to a template created and to `/internal/carriers/<template_sid>/edit`
=> Prefill predefined carrier gateways in a form

src/containers/internal/views/speech-services/form.tsx, src/vendor/speech-synthesis/ibm-speech-synthesis-lang.ts
Fix issue with showing tts api key:
Fix voice List having 3 Kates for en-GB.
=> fix state for tts_api_key and voice typo

src/api/constants.ts, src/api/index.ts, src/api/types.ts, src/components/forms/local-limits.tsx, src/containers/internal/views/settings/service-provider-settings.tsx
@davehorton @kitajchuk This was the code that was lost somehow during the scoping. 
As agreed, we wanted the new call limits under the env VITE_APP_ENABLE_ACCOUNT_LIMITS_ALL to be disabled for non-admin users, and the MAX limits hidden completely.
Account User view with env VITE_APP_ENABLE_ACCOUNT_LIMITS_ALL
Admin user view env VITE_APP_ENABLE_ACCOUNT_LIMITS_ALL
There is still a question on where we should handle the deletion of the limits set the first time that are in contradiction with the new limits set (e.g. we set session limits, then we decide to change to minutes limits the session limits are not deleted all limits we send more limits and all exist in the backend - so the old ones should be deleted). @davehorton @kitajchuk what do you think should we do this in the frontend?
=> Scope optional limits

src/api/index.ts, src/components/forms/local-limits.tsx, src/containers/internal/views/alerts/index.tsx, src/containers/internal/views/recent-calls/details.tsx, src/containers/internal/views/recent-calls/pcap.tsx
"Invalid date" was displayed instead of a title for Alerts and recent calls
The date format received:
{
"call": {
"attempted_at": "2022-12-28T18:43:53.874Z",
"account_sid": "xxx",
"answered": true,
"answered_at": "2022-12-28T18:43:56.841Z",
"application_sid": "xxx",
"call_sid": "xxx",
"direction": "inbound",
"duration": 17,
"from": "+xxxxxxx",
"host": "undefined",
"remote_host": "54.172.60.3",
"service_provider_sid": "2708b1b3-2736-40ea-b502-c53d8396247f",
"sip_callid": "xxxx@0.0.0.0",
"sip_status": 200,
"terminated_at": "2022-12-28T18:44:14.226Z",
"termination_reason": "called party hungup",
"to": "+15082069511",
"trace_id": "xxx",
"trunk": "Twilio"
}
}
=> Date fix for alerts and recent calls

.env, src/api/index.ts, src/containers/internal/views/carriers/form.tsx
Service provider sid was not attached when an account level carrier was created, thus Phone number fetch of carriers did not contain account-related carriers.
This now allows the Account user to create account level Carrier and then add a Phone number.
I still think that we should restrict /SP API to return only relevant account carriers. Now if there are more accounts all will be fetched.
Related PR was created to limit /SP API to scope for both VoipCarriers and Speech Creds
https://github.com/jambonz/jambonz-api-server/pull/96
=> Always attach service_provider_sid to a carrier

src/containers/internal/views/settings/index.tsx, src/containers/internal/views/users/form.tsx
Related PR in jambonz-api-server: https://github.com/jambonz/jambonz-api-server/pull/95
We allow falsy values to be sent and updated. Before api was updating only a truthy value.
=> Fix issue where is_active user & force_change cannot be deactivated

src/api/constants.ts, src/components/forms/passwd/index.tsx, src/containers/internal/navi/items.ts, src/containers/internal/views/accounts/delete.tsx, src/containers/internal/views/accounts/form.tsx, src/containers/internal/views/applications/form.tsx, src/containers/internal/views/carriers/form.tsx, src/containers/internal/views/carriers/index.tsx, src/containers/internal/views/phone-numbers/form.tsx, src/containers/internal/views/recent-calls/index.tsx, src/containers/internal/views/settings/admin-settings.tsx, src/containers/internal/views/settings/index.tsx, src/containers/internal/views/settings/service-provider-settings.tsx, src/containers/internal/views/speech-services/form.tsx, src/containers/internal/views/speech-services/index.tsx
I have applied the same capitalization rule to all app: "only the first word in a phrase should be capitalized".
I also changed "SIP trunk" appearing in one place. We call them Carriers in our new app in all other places.
I have found that the terms "SIP Diversion Header", "SIP Register", "MS Teams Direct Routing" are exceptions since they are supposed to be capitalized in the "Voice world".
What about "SIP from user" and "SIP from domain"?
I have also solved that warning coming up in the console regarding autocompleting the passwords.
Other console errors were due to my own Chrome extension. After disabling it they were gone, so unrelated to the webapp.
=> Improving naming consistency

src/containers/internal/views/alerts/index.tsx, src/containers/internal/views/applications/index.tsx, src/containers/internal/views/carriers/index.tsx, src/containers/internal/views/recent-calls/index.tsx, src/containers/internal/views/speech-services/index.tsx, src/containers/internal/views/users/index.tsx
The Spinner issue appeared everywhere where "accounts" array length was needed. So to reproduce this create a new SP and do not create any accounts, then go to Recent Calls, Alerts, Applications where !hasValue(aplications) will be true if accounts array is empty. 
So now this PR is adding a check that also checks for the length of the Accounts. This fixes the issue of the spinner
=> Spinner spinning forever issue

src/containers/internal/views/applications/edit.tsx, src/containers/internal/views/carriers/index.tsx, src/containers/internal/views/speech-services/form.tsx, src/containers/internal/views/speech-services/index.tsx
This PR combines Carriers and Speech credential lists for account user and disables Filtering according to the account
Account user views for these lists:
API server small change to have Speech /SP call act the same way as Carriers: https://github.com/jambonz/jambonz-api-server/pull/98  This way the implementation is the same.
=> Combine account user lists for carriers and speech

src/utils/use-filtered-results.ts
In user lists, a fuzzy search was not really accurate when it came to searching by name, since names can have different capitalizations. This PR fixes this issue.
=> Fix fuzzy search to match against toLowerCase strings

Dockerfile
This PR upgrades node base image to node:18.14.0-alpine3.16
This fixes:
Critical vulnerability:
CWE-843: Access of Resource Using Incompatible Type ('Type Confusion')
High vulnerability:
CWE-416: Double Free
CWE-416: Use After Free
=> Upgrade node base image

Dockerfile
This PR upgrades node base image to node:18.14.0-alpine3.16
This fixes:
Critical vulnerability:
CWE-843: Access of Resource Using Incompatible Type ('Type Confusion')
High vulnerability:
CWE-416: Double Free
CWE-416: Use After Free
=> Upgrade legacy app with new node image

.env, src/containers/internal/views/carriers/form.tsx, src/utils/index.ts
This PR adds the option to disable Default Application options to prevent SP and Account level users from configuring a default route to an application if needed.
Env VITE_APP_DISABLE_DEFAULT_TRUNK_ROUTING will hide "Default application" dropdown in Carrier Edit form when Account in "Used by" field is selected.
=> Add env VITE_APP_DISABLE_DEFAULT_TRUNK_ROUTING

src/api/constants.ts, src/api/index.ts, src/router/auth.tsx
Until now we did not call Logout when signing out, thus the jwt was expiring only after the expiration time, not after login directly.
=> Add Logout call to signout

src/containers/internal/navi/index.tsx, src/containers/internal/views/accounts/form.tsx, src/utils/index.ts
When as admin you were trying to add Account with the same name as account in a different SP it was failing.
How to test:
1. login as admin
2. create another SP
3. try creating an account with the same name as an account in the default SP
I also added a hard reload when changing service provider in the dropdown.
When you were in an edit form or so, when changing SP it was staying within the form causing a wrong fetch. 
Also, enhanced the password check to be same as in api-server regarding the special chars.
=> fix the webapp blocking account name if exists in anohter SP

src/containers/internal/views/users/form.tsx
Account users were not able to add other account users, because State didn't have accountSid selection automatically.
=> Add a fallback accountSid for account users

src/components/forms/checkzone/index.tsx
#241 
Hi @davehorton 
The issue is that the unchecked checkzone still redener input with required class.
fixed it by, if it's unchecked checkzone, no redender for all children component.
=> fix: unchecked checkzone still render input with required

src/api/constants.ts
0 - default mode (no latency optimizations)
1 - normal latency optimizations (about 50% of possible latency improvement of option 3) 
2 - strong latency optimizations (about 75% of possible latency improvement of option 3) 
3 - max latency optimizations 
4 - max latency optimizations, but also with text normalizer turned off for even more latency savings (best latency, but can mispronounce eg numbers and dates).
=> fix default value for elevenlab optimize_streaming_latency

src/api/types.ts, src/components/forms/checkzone/index.tsx, src/containers/internal/views/speech-services/form.tsx
https://github.com/jambonz/jambonz-webapp/issues/397
=> Support deepgram onprem

src/styles/_forms.scss
https://github.com/jambonz/jambonz-webapp/issues/429
Before
After
=> fix send OPTIONS ping mess the layout

src/api/types.ts, src/containers/internal/views/speech-services/form.tsx
https://github.com/jambonz/freeswitch-modules/issues/93
=> support deepgram on-prem

src/api/constants.ts, src/containers/internal/views/recent-calls/index.tsx
=> support recents call dropdown filter to have yesterday option

src/containers/internal/views/applications/speech-selection.tsx
Step to reproduce:
1/ create cartesia speech credntial
2/ update application to use cartesia
3/ application will choose default english language and voice
4/ change the language to french and french voice as well.
5/ save the application and go to Recent call
6/ go back to recent call and see that the synthesizer is change to default english again but data return from backend still showing fr language and voice.
=> fix: application synthsizer configuraiton is shown different than data stored in db  when view application.

src/containers/internal/views/alerts/index.tsx
fixed an error when "yesterday" option is selected as the api is called with NaN. Also added all options from the DATE_SELECTION constants
@xquanluu @davehorton @vinoddharashive
=> fixed error when selecting yesterday option from date filter

src/components/forms/passwd/index.tsx, src/containers/login/login.tsx
add the data-lpignore attribute to the password component and remove redundant {} on autoComplete.
This should resolve the recurring issue we've had with users having issues creating a carrier where the page was expecting an SMPP IP adddress, that issue seemed to be that lastpass was adding their jambonz password as an SMPP password so the form validation expected an SMPP IP to go with the credentials.
By default lastpass don't honor the autocompete=off attribute unless you change your settings but they also have this aditional attribute which should then ignore the field for all lastpass users 
https://support.lastpass.com/s/document-item?language=en_US&bundleId=lastpass&topicId=LastPass/c_lp_prevent_fields_from_being_filled_automatically.html&_LANG=enus
=> Disable password managers on some password forms
