- Dockerfile
- entrypoint.sh
- package.json
Created a new Dockerfile
Environment variables can override defaults for:
- API_PORT
- API_VERSION
- HTTP_PORT
- REACT_APP_API_BASE_URL
External IP is automatically set if you do not set the REACT_APP_API_BASE_URL
> created Dockerfile and entrypoint with default http port

- Dockerfile
> use python3 package

- src/components/pages/internal/RecentCallsList.js
This is to achieve feature parity with `jambonz-webapp-com` PR:
https://github.com/jambonz/jambonz-webapp-com/pull/42
> Adding pcap file download button to RecentCalls view

- package-lock.json
fixes all high and critical security updates
> fix security vulnerabilities

- src/components/forms/AccountForm.js
Resolves errors in js console and admin portal when clicking 'Add Account' button
fixes #36
> fix add account error message

- src/components/forms/SpeechForm.js
Removed vendor radio buttons and replaced with a dropdown menu
fixes #52
> removed radio buttons, replaced with dropdown

- src/data/MicrosoftAzureRegions.js
> Update Azure speech list

- src/containers/internal/api-keys/index.tsx
- src/containers/internal/views/accounts/delete.tsx
- src/containers/internal/views/accounts/index.tsx
- src/containers/internal/views/applications/index.tsx
- src/containers/internal/views/settings/index.tsx
- src/containers/internal/views/speech-services/index.tsx
- src/utils/index.ts
Adding some simple utility functions to make some conditional checks better at the component-level.
> Adding some conditional utilities

- src/api/index.ts
- src/api/types.ts
- src/containers/internal/views/ms-teams-tenants/add.tsx
- src/containers/internal/views/ms-teams-tenants/delete.tsx
- src/containers/internal/views/ms-teams-tenants/edit.tsx
- src/containers/internal/views/ms-teams-tenants/form.tsx
- src/containers/internal/views/ms-teams-tenants/index.tsx
- src/router/index.tsx
#74 
Just a quick copy-paste job. I still make sure that it works. Unless there are some places to poke.
> Microsoft Tenant page for refresh

- package.json
update moment lib from 2.29.1 to 2.29.4
> update moment lib

- src/api/constants.ts
- src/components/icons.ts
- src/containers/internal/views/alerts/index.tsx
#76 
A really quick copy paste work.
No style for the table, as always.
I am sort of concerned of this `useEffect()`. It seems really adventurous.
https://github.com/jambonz/jambonz-webapp/blob/c29087ac9ecae0dde5682e2f2018325790bac8ae/src/containers/internal/views/alerts/index.tsx#L63-L72
Seems like we can call the `handleFilterChange()` in the former `useEfflect()` also?
> Alert view page for refresh 

- src/api/constants.ts
- src/components/pagination/index.tsx
#100 
This is what I really wanted to get done when I was working on the recent calls.
It is not quite showing at least how many button as I realize it would introduce some really complex logic. This would feel better than what the pagination is now.
> Refresh enhancement pagination logic

- src/containers/internal/views/ms-teams-tenants/form.tsx
- src/containers/internal/views/ms-teams-tenants/index.tsx
- src/containers/internal/views/phone-numbers/index.tsx
See issue here: https://github.com/jambonz/jambonz-webapp/issues/113
> Fix MS Teams view bug for #113

- .github/workflows/pr-checks.yml
- .gitignore
- .husky/pre-commit
- cypress.config.ts
- cypress/fixtures/accounts.json
- cypress/fixtures/applications.json
- cypress/support/commands.ts
- cypress/support/component-index.html
- cypress/support/component.ts
- docs/contributors.md
- package-lock.json
- package.json
- src/components/access-control.cy.tsx
- src/components/access-control.tsx
- src/components/account-filter.cy.tsx
- src/components/account-filter.tsx
- src/components/application-filter.cy.tsx
- src/components/application-filter.tsx
- src/components/select-filter.cy.tsx
- src/main-app.tsx
- src/main.tsx
- src/store/actions.ts
- src/utils/index.ts
- tsconfig.json
See issue here: https://github.com/jambonz/jambonz-webapp/issues/102
> Implement initial Cypress testing configuration

- cypress/fixtures/userLogin.json
- cypress/support/component.tsx
- src/api/types.ts
- src/components/access-control.cy.tsx
- src/components/require-auth.cy.tsx
- src/components/scoped-access.cy.tsx
- src/components/scoped-access.tsx
- src/containers/internal/navi/index.tsx
- src/store/actions.ts
- src/store/index.tsx
- src/store/types.ts
- src/styles/_grid.scss
- src/test/index.tsx
@EgleHelms Here's an okay implementation of the tests for this component. I realized when trying to set things up how I imagined that we can't quite do it that way since our store is using `useReducer` and is not easily mockable. Anyway, one simple fix here is to just pass the user as a prop on the component which allows us to write tests. I think this is fine for now.
> Tests for ScopedAccess

- cypress/fixtures/userLogin.json
- cypress/support/component.tsx
- package.json
- src/api/types.ts
- src/components/access-control.cy.tsx
- src/components/require-auth.cy.tsx
- src/components/scoped-access.cy.tsx
- src/components/scoped-access.tsx
- src/containers/internal/navi/index.tsx
- src/store/actions.ts
- src/store/index.tsx
- src/store/types.ts
- src/styles/_grid.scss
- src/test/index.tsx
- tsconfig.json
@kitajchuk this is my try to implement what you described with a simple component, plus applied it as an example in one place which works well in the app itself. I also added a similar cypress test, but that one does not render for some reason (I find that strange since it works in the app), maybe you can spot why with your pro eyes :).
I was not exactly sure about the hook and what exactly you meant about that. Maybe you can let me know where we would use it. Now I didn't think this was nescesarry.
Let me know your thoughts. And many thanks for guiding me.
> ScopeAccess component implementation

- src/api/types.ts
- src/containers/internal/views/speech-services/form.tsx
- src/vendor/index.tsx
- src/vendor/regions/ibm-regions.ts
- src/vendor/speech-recognizer/ibm-speech-recognizer-lang.ts
- src/vendor/speech-synthesis/ibm-speech-synthesis-lang.ts
- src/vendor/types.ts
- Added to Speech form
- Added to Application form
Was not sure about the util this time either. Since I didnt need to add to make the conditionals bigger.
> Add IBM as speech provider

- .env
- src/api/constants.ts
- src/api/types.ts
- src/components/forms/local-limits.tsx
Optional env is: VITE_APP_ENABLE_ACCOUNT_LIMITS_ALL
Enables new choosing units and getting accordingly the new fields:
> Optional account call limits

- src/api/index.ts
- src/containers/internal/views/applications/index.tsx
- src/containers/internal/views/carriers/form.tsx
- src/containers/internal/views/carriers/index.tsx
- src/containers/internal/views/speech-services/form.tsx
- src/containers/internal/views/speech-services/index.tsx
- src/containers/internal/views/speech-services/status.tsx
- src/utils/index.ts
Refactor conditional apiUrl logic -- add apiPath to deps in useApiData hook
> Refactor scope/limits branch

- src/api/index.ts
- src/constants/index.tsx
- src/containers/internal/layout.tsx
- src/containers/login/login.tsx
- src/router/auth.tsx
This fixes our logout by using a hard redirect while still flashing the successful logout toast 👍
> Fix logout with hard redirect -- dump state

- src/api/types.ts
- src/containers/internal/views/speech-services/form.tsx
This PR adds an Instance ID field to IBM Speech form and is required for STT.
> Add Instance ID field to IBM Speech

- src/containers/internal/views/applications/form.tsx
> fix: edit application does not clear webhook user/pass when checkbox is uncheck

- src/api/constants.ts
- src/api/index.ts
- src/api/types.ts
- src/containers/internal/views/carriers/form.tsx
- src/containers/internal/views/carriers/index.tsx
- src/containers/internal/views/carriers/pcap.tsx
- src/containers/internal/views/carriers/register-status.tsx
> feat: carrier register status

- src/api/constants.ts
- src/api/types.ts
- src/containers/internal/views/carriers/form.tsx
- src/styles/_forms.scss
> feat: add sip gateway protocol for outbound traffic

- src/containers/internal/views/least-cost-routing/add.tsx
- src/containers/internal/views/least-cost-routing/edit.tsx
> fix: add/edit lcr should have secondary text to explain the purpose of lcr

- src/api/constants.ts
- src/api/index.ts
- src/api/types.ts
- src/containers/internal/views/settings/admin-settings.tsx
> feat: admin clear cache

- src/containers/internal/views/recent-calls/details.tsx
> feat: add seconds to recent call sumary

- src/constants/index.tsx
- src/containers/login/create-password.tsx
The Create password error was hard coded.
I moved it and used passwordSettings to tell the user what is wrong with the password.
> Hint passwordSettings to user when creating password

- src/vendor/speech-synthesis/google-speech-synthesis-lang.ts
> feat/ update google tts voice for neutral and studio

- src/containers/internal/views/least-cost-routing/card.tsx
- src/containers/internal/views/recent-calls/index.tsx
> recent call filter

- src/containers/internal/views/carriers/form.tsx
https://github.com/jambonz/sbc-sip-sidecar/issues/35
> fix: update name for carrier register authentication fields

- src/containers/internal/views/recent-calls/details.tsx
> only download jaeger trace when open detail for recent call

- src/api/constants.ts
- src/api/types.ts
- src/containers/internal/views/accounts/form.tsx
https://github.com/jambonz/jambonz-webapp/issues/291
> feat: google storage for record all call

- src/components/domain-input/index.tsx
- src/components/domain-input/styles.scss
- src/containers/internal/views/accounts/edit-sip-realm.tsx
- src/containers/internal/views/carriers/index.tsx
- src/containers/login/sub-domain.tsx
> fix choose/edit sub domain

- src/containers/internal/views/accounts/manage-payment-form.tsx
- src/containers/internal/views/accounts/subscription-form.tsx
> allow only card type in stripe PaymentElement

- index.html
> update preview description

- src/api/constants.ts
- src/api/types.ts
- src/containers/internal/views/accounts/form.tsx
https://github.com/jambonz/jambonz-webapp/issues/306
> support azure storage

- src/api/types.ts
- src/containers/internal/views/applications/form.tsx
- src/containers/internal/views/applications/speech-selection.tsx
https://github.com/jambonz/jambonz-feature-server/issues/425
> feat fallback speech vendor

- src/api/index.ts
- src/containers/internal/views/recent-calls/player.tsx
- src/containers/internal/views/recent-calls/styles.scss
> support delete record file

- src/api/types.ts
- src/containers/internal/views/speech-services/form.tsx
- src/utils/index.ts
https://github.com/drachtio/drachtio-freeswitch-modules/issues/126#event-10009635698
> feat azure fromhost

- src/containers/internal/views/applications/form.tsx
- src/containers/internal/views/applications/speech-selection.tsx
> feat: custom Microsoft need to have input text for tts voice

- src/api/types.ts
- src/containers/internal/views/carriers/form.tsx
- src/styles/_forms.scss
> pad crypto sip gateway

- src/api/types.ts
- src/containers/internal/views/carriers/form.tsx
https://github.com/jambonz/jambonz-webapp/issues/321
> allow sip port is null

- src/containers/internal/views/applications/speech-selection.tsx
- src/vendor/index.tsx
> fix cobalt default language

- src/styles/_filters.scss
https://github.com/jambonz/jambonz-webapp/issues/285
> fix css for recent calls in small screen

- src/containers/internal/views/accounts/index.tsx
- src/containers/internal/views/applications/index.tsx
- src/containers/internal/views/carriers/index.tsx
- src/containers/internal/views/clients/index.tsx
- src/containers/internal/views/least-cost-routing/index.tsx
- src/containers/internal/views/ms-teams-tenants/index.tsx
- src/containers/internal/views/phone-numbers/index.tsx
- src/containers/internal/views/speech-services/index.tsx
- src/containers/internal/views/users/index.tsx
> fix wrong css for filter on each component

- src/containers/internal/views/clients/form.tsx
https://github.com/jambonz/jambonz-feature-server/issues/489
> remove warning message if there is no device call application

- src/api/constants.ts
- src/api/index.ts
- src/api/types.ts
- src/containers/internal/views/applications/form.tsx
- src/containers/internal/views/applications/speech-selection.tsx
- src/containers/internal/views/speech-services/form.tsx
- src/styles/_forms.scss
https://github.com/jambonz/jambonz-webapp/issues/337
> feat google custom voice

- src/api/index.ts
- src/api/types.ts
- src/constants/index.tsx
- src/containers/internal/views/least-cost-routing/container.tsx
- src/containers/internal/views/least-cost-routing/form.tsx
https://github.com/jambonz/jambonz-webapp/issues/347
> fix lcr create update generate too much request

- src/containers/internal/views/applications/speech-selection.tsx
https://github.com/jambonz/jambonz-webapp/issues/352
> fix elevenlabs set voice

- src/containers/internal/views/carriers/register-status.tsx
IF there is something wrong on carrier registration status, we still can show the status
> fix carrier registration status

- src/api/constants.ts
- src/api/types.ts
- src/containers/internal/views/speech-services/form.tsx
- src/vendor/speech-synthsis-models/elevenlabs-models.ts
https://github.com/jambonz/jambonz-feature-server/issues/541
> elevenlabs new model and options

- src/api/jaeger-types.ts
- src/containers/internal/views/recent-calls/player.tsx
> tts latency feature

- src/containers/internal/views/applications/speech-selection.tsx
- src/containers/internal/views/speech-services/form.tsx
- src/vendor/index.tsx
- src/vendor/speech-synthsis-models/deepgram-models.ts
- src/vendor/types.ts
> support deepgram

- src/containers/internal/views/applications/speech-selection.tsx
https://github.com/jambonz/jambonz-webapp/issues/368
> fix application choose speech credential if all credential are labeled

- src/containers/internal/views/applications/speech-selection.tsx
https://github.com/jambonz/jambonz-webapp/issues/367
> fix, change synthLange does not update synthVoice

- src/vendor/speech-synthesis/google-speech-synthesis-lang.ts
https://github.com/jambonz/jambonz-webapp/pull/373
> update google tts language

- src/containers/internal/views/applications/form.tsx
- src/containers/internal/views/applications/speech-selection.tsx
https://github.com/jambonz/jambonz-webapp/issues/378
> fix remove speech label, cause application save wrong label

- src/api/jaeger-types.ts
- src/containers/internal/views/recent-calls/player.tsx
https://github.com/jambonz/jambonz-webapp/issues/382
> gather speech verb hook latency

- src/containers/internal/views/recent-calls/player.tsx
> wavesurfer region use s instead of sec

- src/containers/internal/views/recent-calls/player.tsx
> draw tts region label to lower possition

- src/containers/internal/views/accounts/form.tsx
> issue/409, shoud not get Invoices in self-hosted system

- src/vendor/regions/ms-azure-regions.ts
> update azure speech regions

- src/api/types.ts
- src/containers/internal/views/carriers/form.tsx
> register use tls

- src/api/constants.ts
- src/api/types.ts
- src/containers/internal/views/speech-services/form.tsx
- src/vendor/index.tsx
- src/vendor/types.ts
> support mod_playht_tts

- src/containers/internal/views/recent-calls/jaeger/bar.tsx
- src/containers/internal/views/recent-calls/jaeger/detail.tsx
https://github.com/jambonz/jambonz-webapp/issues/421
> print streaming tts span details

- src/api/constants.ts
- src/api/types.ts
- src/containers/internal/views/speech-services/form.tsx
- src/vendor/index.tsx
- src/vendor/types.ts
> support verbio speech

- LICENSE
- src/api/types.ts
- src/containers/internal/views/carriers/form.tsx
> add use sips scheme to outbound tls gateway

- .env
- src/api/types.ts
- src/containers/internal/views/settings/admin-settings.tsx
- src/utils/index.ts
https://github.com/jambonz/sbc-inbound/issues/157
> support admin settings private network CIDR

- .env
- src/containers/internal/views/carriers/form.tsx
https://github.com/jambonz/sbc-inbound/issues/159
> sip gateways support inbound pad crypto

- src/api/constants.ts
- src/api/index.ts
- src/api/types.ts
- src/containers/internal/views/speech-services/form.tsx
- src/styles/_forms.scss
> support add google voice cloning key

- src/containers/internal/views/speech-services/index.tsx
https://github.com/jambonz/jambonz-feature-server/issues/940
Removed the last used column, please see attached picture
> feat/940: Removed last_used column from speech services

- src/api/constants.ts
- src/api/types.ts
- src/containers/internal/views/carriers/form.tsx
> support carrier dtmf type selection

- src/api/constants.ts
- src/api/types.ts
- src/containers/internal/views/applications/speech-selection.tsx
- src/containers/internal/views/speech-services/form.tsx
- src/vendor/index.tsx
- src/vendor/types.ts
https://github.com/jambonz/jambonz-webapp/issues/470
> support tts cartesia

- src/api/types.ts
- src/containers/internal/views/speech-services/form.tsx
https://github.com/jambonz/jambonz-feature-server/pull/1023
> support custom tts streaming

- src/containers/internal/views/applications/speech-selection.tsx
- src/containers/internal/views/speech-services/form.tsx
- src/vendor/index.tsx
- src/vendor/types.ts
https://github.com/jambonz/jambonz-feature-server/pull/1066
> support voxist stt

- src/api/types.ts
- src/containers/internal/views/carriers/form.tsx
- src/utils/index.ts
> Support voip carrier sip proxy

- src/containers/internal/views/phone-numbers/form.tsx
https://jambonz.freshdesk.com/a/tickets/649
> filter carrier based on account_sid when creating phone number

- src/containers/internal/views/applications/form.tsx
> improvements when entering application call hook

- .env
- src/api/types.ts
- src/containers/internal/views/applications/speech-selection.tsx
- src/containers/internal/views/speech-services/form.tsx
- src/vendor/index.tsx
- src/vendor/types.ts
> support openAi stt

- src/containers/internal/views/applications/speech-selection.tsx
https://github.com/jambonz/jambonz-webapp/issues/504
> support rimelabs arcana

- .env
- src/api/constants.ts
- src/api/index.ts
- src/api/types.ts
- src/containers/internal/views/applications/form.tsx
> support applicatin env vars

- src/api/types.ts
- src/containers/internal/views/applications/form.tsx
https://github.com/jambonz/jambonz-webapp/issues/512
> fixed PUT of env_vars in Applications should not stringify

- src/containers/internal/views/accounts/form.tsx
https://jambonz.freshdesk.com/a/tickets/880
> fix enable recording feature replace obscurbed value to input text after user edit it and test

- src/api/types.ts
- src/components/obscure-input/index.tsx
- src/components/obscure-input/styles.scss
- src/containers/internal/views/applications/form.tsx
> support App envs obscured input text

- src/containers/internal/views/carriers/form.tsx
> fixed carrier sip proxy can't add port

- src/api/types.ts
- src/containers/internal/views/applications/form.tsx
- src/styles/_forms.scss
> support uiHInt property in env vars

- .env
- src/containers/internal/views/carriers/delete.tsx
- src/containers/internal/views/least-cost-routing/form.tsx
https://jambonz.freshdesk.com/a/tickets/974
> fixed Cannot delete Carrier, show message that there is link to LCR

- src/containers/internal/views/applications/speech-selection.tsx
> fix regression bug: new app does not save tts voice by default

- src/api/types.ts
- src/containers/internal/views/speech-services/form.tsx
> support mod cartesia transcribe

- src/api/constants.ts
- src/api/types.ts
- src/containers/internal/views/speech-services/form.tsx
https://github.com/jambonz/jambonz-feature-server/issues/1257
> support assemblyai v3

- src/containers/internal/views/recent-calls/player.tsx
> Draw STT latency to recording player by using stt metrics from opentelemetry

- .env
- src/api/constants.ts
- src/containers/internal/views/speech-services/form.tsx
> support deepgram EU-hosted STT

- src/api/types.ts
- src/containers/internal/views/applications/speech-selection.tsx
- src/containers/internal/views/speech-services/form.tsx
- src/vendor/index.tsx
- src/vendor/types.ts
> support resemble tts
